application: gcs-signed-url
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# https://gcs-signed-url.appspot.com/admin/interactive
- url: /admin.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
